version: "3.5"

services:
  api01: &api
    image: accerqueira/rinha-de-backend-2024-q1-api
    build:
      dockerfile: Dockerfile
      args:
        - SOURCE_PATH=src/api/
    depends_on:
      - db
    environment:
      - DB_CONNECTION_URL=http://127.0.0.1:8083
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "10MB"
    command: -p 8081 -u -s

  api02:
    <<: *api
    command: -p 8082 -u -s

  lb:
    image: accerqueira/rinha-de-backend-2024-q1-lb
    build:
      dockerfile: Dockerfile
      args:
        - SOURCE_PATH=src/lb/
    depends_on:
      - api01
      - api02
    environment:
      - SERVERS=http://127.0.0.1:8081|http://127.0.0.1:8082
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "20MB"
    command: -p 9999 -u -s

  db:
    image: accerqueira/rinha-de-backend-2024-q1-db
    build:
      dockerfile: Dockerfile
      args:
        - SOURCE_PATH=src/db/
    network_mode: host
    environment:
      - DB_INIT_SCRIPT=
        CREATE TABLE IF NOT EXISTS clientes (
          "id" INTEGER PRIMARY KEY NOT NULL,
          "saldo" INTEGER NOT NULL,
          "limite" INTEGER NOT NULL,
          "ultimas_transacoes" JSON NOT NULL DEFAULT ('[]')
        );
        DELETE FROM clientes;
        INSERT INTO clientes VALUES(1,0,100000,'[]');
        INSERT INTO clientes VALUES(2,0,80000,'[]');
        INSERT INTO clientes VALUES(3,0,1000000,'[]');
        INSERT INTO clientes VALUES(4,0,10000000,'[]');
        INSERT INTO clientes VALUES(5,0,500000,'[]');
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "20MB"
    command: -p 8083 -u -s
